services:  
  # Container now based on nginx-proxy
  nginx:
    profiles:
      - live
    image: nginxproxy/nginx-proxy:1.5
    container_name: dean-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERTS:-./certs}:/etc/nginx/certs:ro
    restart: unless-stopped
    # environment:
    #   - DEFAULT_ROOT=301 https://google.com   # Not working?

  nginx-dev:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: dean-nginx-dev
    profiles:
      - dev
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt



  # Old manual configuration
  nginx-v1: 
    profiles:
      - v1
    container_name: dean-nginx-v1
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./v1/conf:/etc/nginx/conf.d:ro
      - ${CERTS_V1:-./certs/}:/etc/nginx/ssl:ro