services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./mounts/acme:/var/www/certbot:rw
      - ./mounts/certbot:/etc/letsencrypt:rw
    entrypoint: certbot certonly --webroot --webroot-path /var/www/certbot/ -m $EMAIL -d $CERT_DOMAINS --agree-tos