name: dean-server
services:  
  # Container now based on nginx-proxy
  nginx:
    image: nginxproxy/nginx-proxy:1.6
    container_name: dean-nginx
    hostname: dean-nginx
    profiles:
      - live
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ${CERTS:-./mounts/certs}:/etc/nginx/certs:ro
      - ./public:/public:ro                       # To serve files, the directory and files must have execute permissions
      - ./mounts/logs:/var/log/nginx
      - ./mounts/acme:/usr/share/nginx/html:ro    # The path nginx-proxy uses for certificate validation
      - /etc/localtime:/etc/localtime:ro          # Sync time with host
    # environment:
    #   DEFAULT_ROOT: 301 https://google.com        # Not working?
    

  # Certbot - For manual certificate generation without taking the HTTP proxy down
    # Using Let'sEncrypt 
  certbot:
    profiles:
      - cert
    extends: 
      file: compose.certbot.yml
      service: certbot

  certbot-test:
    profiles:
      - cert-test
    extends: 
      file: compose.certbot.yml
      service: certbot
    container_name: certbot-test
    hostname: certbot-test
    command: --dry-run