name: dean-server
services:  
  # Container now based on nginx-proxy
  nginx:
    profiles:
      - live
    image: nginxproxy/nginx-proxy:1.5
    container_name: dean-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/live/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ${CERTS}:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
      - ./public:/public:ro           # To serve files, the directory and files must have execute permissions
    restart: unless-stopped
    # environment:
    #   - DEFAULT_ROOT=301 https://google.com   # Not working?
    

  # Legacy version - Manual nginx configuration
  nginx-legacy: 
    profiles:
      - legacy
    container_name: dean-nginx-legacy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/legacy:/etc/nginx/conf.d:ro
      - ${CERTS_LEGACY:-./certs/}:/etc/nginx/ssl:ro